### ISSUE TITLE
Create Classroom-Multipurpose or Classroom-Lecture room type terms

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/registrar.uiowa.edu#10]
And map in feed.

**Comment by briand44** [comment]
https://github.com/ITS-UofIowa/registrar.uiowa.edu/commit/735d8f97fb4268ca2ccecbd8f1362eb48cc4f171

I noticed that now there are not any conference rooms. On the prod site there are currently two conference rooms. One is now classroom multipurpose the other (krc 2d) does not have a room type now. In MAUI it is listed as "Meeting Room", but we don't have a Meeting Room type.

**Comment by briand44** [comment]
Not sure if we want to remove the Classroom room type in an update hook or not. I can't remove it currently on the production site because it is in use but I'm guessing we will want to remove it at some point.
