### ISSUE TITLE
Implement minimum & maximum range for the filter

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/registrar.uiowa.edu#15]
Assumed for capacity.

**Comment by briand44** [comment]
https://github.com/ITS-UofIowa/registrar.uiowa.edu/commit/45b7207f583dc5ee29bdc777019e6a22cd7e7e9a adds the filter and https://github.com/ITS-UofIowa/registrar.uiowa.edu/commit/8361a8cf8bd14e85ef6faca2174bac5c35601e05 themes the filter.
