### ISSUE TITLE
UC CSV exporting to Notepad

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/registrar.uiowa.edu#17]
Check file extension.

**Comment by briand44** [comment]
The file downloads as a csv and opens in excel for me. Maybe they just need to tell their machine to use excel to open csv files?

**Comment by briand44** [comment]
Lets have them verify the file type once they download the file.

**Comment by richardbporter** [comment]
Resolved by https://github.com/ITS-UofIowa/registrar.uiowa.edu/commit/2bd503476ac6987a1f9e3973a2488ddfcc869b9f
